cc_test(
    name = "log",
    size = "small",
    srcs = glob(["*.cc"]),
    features = ["treat_warnings_as_errors"],
    deps = [
        "//source/cortecs/log",
        "@googletest//:gtest",
        "@googletest//:gtest_main",
    ],
)
