cc_test(
    name = "string",
    size = "small",
    srcs = glob(["*.cc"]),
    features = ["treat_warnings_as_errors"],
    deps = [
        "//source/cortecs/string",
        "@googletest//:gtest",
        "@googletest//:gtest_main",
    ],
)
