# cc_test(
#     name = "json",
#     size = "small",
#     srcs = glob(["*.cc"]),
#     features = ["treat_warnings_as_errors"],
#     deps = [
#         "//source/cortecs/json",
#         "@googletest//:gtest",
#         "@googletest//:gtest_main",
#     ],
# )
