cc_test(
    name = "gc",
    size = "small",
    srcs = glob(["*.cc"]),
    features = ["treat_warnings_as_errors"],
    deps = [
        "//source/cortecs/gc",
        "@googletest//:gtest",
        "@googletest//:gtest_main",
    ],
)
