name: Update calver
run-name: Update calver
on: 
  schedule:
    - cron: "0 6 * * *"
jobs:
  update-calver:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ssh-key: ${{ secrets.SSH_KEY }}
      - uses: actions/setup-python@v5
        with: 
          python-version: '3.x'
      - run: pip install GitPython
      - run: git config user.name "VersionBot"
      - run: git config user.email "<>"
      - run: python .github/calver/update-calver.py
      - run: git push --force-with-lease
